[package]
name = "rust_forth"
version = "0.2.0"
authors = ["Frederick Price <rprice@pricemail.ca>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
